/* Automatically generated by './build/bin/build-entry.js' */

import Button from '../packages/button/index.js';
import Toast from '../packages/toast/index.js';

const components = [
  Button,
  Toast
];

const install = function(Vue, opts = {}) {
  components.forEach(component => {
    Vue.component(component.name, component);
  });

  Vue.prototype.$ELEMENT = {
    size: opts.size || '',
    zIndex: opts.zIndex || 2000
  };

};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

export default {
  install,
  Button,
  Toast
};
